SET SQL_SAFE_UPDATES = 0;
DELETE FROM `test-database`.`generos`;
SET SQL_SAFE_UPDATES = 1;

INSERT INTO `test-database`.`generos`(nome) VALUES
('Indie'),
('Ação'),
('Aventura'),
('Casual'),
('Simulação'),
('Estratégia'),
('RPG'),
('Um Jogador'),
('Acesso Antecipado'),
('Gratuito para Jogar'),
('2D'),
('Atmosférico'),
('Violento'),
('Esportes'),
('Multijogador Massivo'),
('Multijogador'),
('Quebra-cabeça'),
('Boa Trama'),
('3D'),
('Fantasia'),
('Gráficos Pixelados'),
('Corrida'),
('Colorido'),
('Violência Detalhada'),
('Nudez'),
('Conteúdo Sexual'),
('Anime'),
('Exploração'),
('Fofo'),
('Primeira Pessoa'),
('Engraçado'),
('Ficção Científica'),
('Arcade'),
('Tiro'),
('Terror'),
('Trilha Sonora Boa'),
('Infantil'),
('Retrô'),
('Relaxante'),
('Mundo Aberto'),
('Cooperativo'),
('Plataforma'),
('Ação / Aventura'),
('Sobrevivência'),
('Difícil'),
('RV'),
('Protagonista Mulher'),
('Terceira Pessoa'),
('Combate'),
('Comedy'),
('Velha-guarda'),
('Tiro em Primeira Pessoa (FPS)'),
('Jogador x Jogador (PvP)'),
('Estilizado'),
('Romance Visual'),
('Cooperativo Online'),
('Você decide'),
('Realístico'),
('Física'),
('Controle'),
('Visão Superior'),
('Sombrio'),
('Faça o que Quiser'),
('Mistério'),
('Personalização de Personagens'),
('Cartunizado'),
('Mandando Bala'),
('Terror Psicológico'),
('Vários Finais'),
('Tático'),
('Design e Ilustração'),
('Espacial'),
('Plataformas 2D'),
('Utilitários'),
('Minimalista'),
('Construção'),
('Jogador x Inimigo (PvE)'),
('Apontar e Clicar'),
('Multijogador Local'),
('Linear'),
('Gerenciamento'),
('Futurista'),
('Mágica'),
('RPG de Ação'),
('Em Turnos'),
('Anos 80'),
('Fabricação'),
('Desenhado à mão'),
('Educativo'),
('Alta Rejogabilidade'),
('Câmera Lateral'),
('Geração Procedural'),
('Desenho Animado'),
('Plataforma com Quebra-cabeça'),
('Medieval'),
('Gerenciamento de Recursos'),
('Terror de Sobrevivência'),
('Para Adultos'),
('Zumbi'),
('Cooperativo Local');