SET SQL_SAFE_UPDATES = 0;
DELETE FROM `test-database`.`jogos`;
SET SQL_SAFE_UPDATES = 1;

INSERT INTO `test-database`.`jogos`(empresa, nome, dt_lancamento) VALUES
(RAND()*49 + 10, TRIM('Pacman                                 '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Tetris                                 '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Wii Sports                             '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Sonic the HedgeHog                     '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('The Sims                               '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Diablo III                             '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Super Mario Bros.                      '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Super Smash Brothers                   '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Pokemon                                '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('The Legend of Zelda                    '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Metal Gear Solid                       '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Halo                                   '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Final Fantasy                          '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Call of Duty                           '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Angry Birds                            '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Skyrim                                 '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Grand Theft Auto                       '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('WoW                                    '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('CounterStrike                          '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Minecraft                              '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('The Oregon Trail                       '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Pong                                   '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Zork                                   '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Space Invaders                         '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Asteroids                              '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Maze 2 (fuckin\' legend)               '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Centipede                              '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Joust                                  '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Maze                                   '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Lode Runner                            '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Elite                                  '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Gauntlet                               '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM(' Platform                              '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Bubble Bobble                          '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Contra                                 '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Mega Man 2                             '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Prince of Persia                       '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('The Secret of Monkey Island            '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Another World                          '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Dune II                                '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Kart racing                            '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Day of the Tentacle                    '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Donkey Kong Country                    '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Space flight simulator                 '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Chrono Trigger                         '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Civilization II                        '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Castlevania: Symphony of the Night     '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Dance Dance Revolution                 '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Age of Empires II                      '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Baldurs Gate II: Shadows of Amn       '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Advance Wars                           '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('The Elder Scrolls III: Morrowind       '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Beyond Good & Evil                     '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Burnout 3: Takedown                    '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Civilization IV                        '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Company of Heroes                      '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('BioShock                               '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Braid                                  '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Limbo                                  '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Batman: Arkham City                    '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Dishonored                             '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Dota 2                                 '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Destiny                                '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Bloodborne                             '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('Inside                                 '), DATE_SUB(CURDATE(), INTERVAL(RAND()*12)*100 MONTH)),
(RAND()*49 + 10, TRIM('The Legend of Zelda: Breath of the Wild'), CURDATE());