SET SQL_SAFE_UPDATES = 0;
DELETE FROM `test-database`.`empresas`;
SET SQL_SAFE_UPDATES = 1;

INSERT INTO `test-database`.`empresas`(nome) VALUES
('Nintendo'),
('Valve Corporation'),
('Rockstar Games'),
('Electronic Arts'),
('Activision Blizzard'),
('Sony Computer Entertainment'),
('Ubisoft'),
('Sega Games Co. Ltd'),
('BioWare'),
('Naughty Dog Inc'),
('Square Enix Holdings Co. Ltd'),
('Capcom Company Ltd'),
('Bungie Inc'),
('Microsoft Corporation'),
('Bandai Namco Entertainment'),
('Mojang'),
('Epic Games'),
('Game Freak'),
('Insomniac Games Inc'),
('Infinity Ward'),
('Take-Two Interactive Software Inc'),
('Gameloft'),
('ZeniMax Media Inc'),
('NCSOFT'),
('Blizzard Entertainment Inc'),
('Zynga'),
('Nexon Co. Ltd'),
('Konami Holdings Corporations'),
('Bethesda Game Studios'),
('Double Fine Productions Inc.'),
('id Software'),
('Rare'),
('Retro Studios'),
('Sonic Team'),
('LucasArts'),
('Level-5 Company'),
('Atari'),
('Thatgamecompany LLC'),
('Beenox'),
('1C Company'),
('EA Maxis'),
('Polyphony Digital'),
('EA Dice'),
('Intelligent Systems Co. Ltd'),
('SCE Santa Monica Studio'),
('EA Canada'),
('PopCap Games'),
('Petroglyph Games'),
('Relic'),
('Treasure Co. Ltd');